##TO RESET THE DATABASE, COPY THIS INTO THE HEROKU PSQL CLIENT

DROP TABLE users;
DROP TABLE posts;

CREATE TABLE users
(
ID SERIAL PRIMARY KEY,
username VARCHAR(20) NOT NULL,
password VARCHAR(20)
);

CREATE TABLE blogposts
(
postid SERIAL PRIMARY KEY,
user_id INT REFERENCES USERS(ID),
post VARCHAR(800),
timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW ()
);
